on:
  push:
    branches:
      - development
name: Deploy to development
jobs:
  FTP-Deploy-Action:
    name: SFTP Upload
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 3
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://jelleglebbeek.com/
        environment: development
    - name: Deploy to SFTP server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.TARGET_SERVER }}
        username: ${{ secrets.TARGET_USER }}
        password: ${{ secrets.TARGET_PASS }}
        port: ${{ secrets.TARGET_PORT }}
        source: "**/**,!.gitignore,!.git/**,!.github/**,!README.md,!LICENSE.txt"
        target: ${{ secrets.TARGET_PATH }}
        overwrite: true
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ github.token }}
        target_url: https://jelleglebbeek.com
        state: success
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ github.token }}
        target_url: https://jelleglebbeek.com
        state: failure
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
